jenkins:
  image: dockerizedrupal/jenkins:1.0.7
  hostname: jenkins
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - jenkins-data
  environment:
    - SERVER_NAME=localhost
    - TIMEZONE=Etc/UTC
    - TIMEOUT=300
    - PROTOCOLS=https,http
jenkins-data:
  image: dockerizedrupal/data:1.0.4
  hostname: jenkins-data
  volumes:
    - /jenkins
