jenkins:
  image: dockerizedrupal/jenkins:1.1.1
  hostname: jenkins
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - jenkins-data
  cap_add:
    - NET_ADMIN
  environment:
    SERVER_NAME: localhost
    TIMEZONE: Etc/UTC
    TIMEOUT: 300
    PROTOCOLS: https,http
    OPENVPN: Off
    OPENVPN_DEVICE: TAP
    OPENVPN_HOST:
    OPENVPN_PORT: 1194
    OPENVPN_USERNAME:
    OPENVPN_PASSWORD:
    OPENVPN_CA_CERTIFICATE:
jenkins-data:
  image: dockerizedrupal/data:1.1.0
  hostname: jenkins-data
  volumes:
    - /jenkins
